### PR TITLE
Bootstrap 3 updates

### PR DESCRIPTION
**Pull request by btsuhako**
Great work on this theme!!

I updated a bunch of libraries for Bootstrap, KnockoutJS, jQuery, etc. Changed the tagging in the main template to display Bootstrap 3 elements. Added additional themes from [Bootswatch](http://bootswatch.com)

### CODE REVIEW

**Comment by aforty** [comment]
Quite the commit, thanks! Love the skin choices by Bootswatch. 

Seeing a few css oddities that may be browser related (latest Chrome, OSX). I prefer the top nav bar to be fixed. Also I was thinking of ditching the top-collapsing menu for a left-panel style menu. 

Do you know if shifting the viewport to the left by some pixels when launching a modal is now a BS3 "feature"? That's hella annoying for someone whose window is always without a scrollbar (OSX). 

A lot of good stuff here, again, give me some time to review, most likely this weekend.

**Comment by btsuhako** [comment]
Yeah, sorry. I'm still getting used to committing to different branches, so everything went into my master this time. I'm getting into the swing of GitHub things, but it's so awesome easily fork from your project! You did all the heavy lifting wiring up everything into Knockout. I've used the Bootswatch themes a couple of times, and they're fantastic.

It's super easy to change the top navbar from static to fixed. I just used my preference.

I'm not sure what you mean about the modal. It reflows to stay in the center of the page when you resize the window and works on mobile devices.

Feel free to take and use whatever. This is now my default theme! Thanks

**Comment by aforty** [comment]
Getting used to git myself, will probably branch and roll your pull request into that. I'll nail it down there before rolling out to everyone.

It's weird. So when I open a modal is shifts all the content thing over by some 15-20px. The shift is abrupt and a more than awkward. Probably a BS3 thing but I'll check it out this weekend. 

Here's a screenshot:

Screenshot

**Comment by btsuhako** [comment]
Yeah, I see what you mean. I didn't notice it when testing. I think it's a BS3 thing, because their website does the same thing, see http://getbootstrap.com/javascript/#modals

**Comment by BeingTomGreen** [comment]
Can this be pulled in now?

I was going to do this but his looks good?

**Comment by aforty** [comment]
Hey @btsuhako, can you redo the pull request for branch "Release 0.6"?

**Pull request closed without merging**
